Repository shelljs/shelljs, pull requests merged in 2018-07, with the labels that each got.

#870 Fix cp from readonly source
  src/cp.js
  test/cp.js
Labels: fix

#871 chore: rename some tests
  test/cp.js
  test/echo.js
Labels: chore

#876 grep includes the i flag
  README.md
  src/grep.js
  test/grep.js
  test/resources/grep/case1
  test/resources/grep/case1.js
  test/resources/grep/case1.txt
Labels: feat
