Repository shelljs/shelljs, pull requests merged in 2018-11, with the labels that each got.

#903 refactor: don't expose tempdir in common.state
  src/common.js
  src/exec.js
  src/tempdir.js
  test/tempdir.js
Labels: refactor

#901 fix: Exit 1 with empty string if no match
  src/grep.js
  test/grep.js
Labels: fix

#907 chore: remove gitter integration
  .travis.yml
Labels: chore

#911 chore(npm): remove lockfile
  .npmrc
  .travis.yml
  appveyor.yml
  package-lock.json
  package.json
  scripts/ci-or-install.js
Labels: chore
