Repository shelljs/shelljs, pull requests merged in 2022-02, with the labels that each got.

#1077 docs(import): document es6 import command
  README.md
Labels: docs, es6

#1078 docs(touch): clarify docs for touch() command
  README.md
  src/touch.js
  test/touch.js
Labels: docs

#1080 Added -L to find to visit symlinked folders too.
  src/find.js
  test/find.js
  test/resources/find/dir2_link
Labels: feature, bash compat
