Repository shelljs/shelljs, pull requests merged in 2022-01, with the labels that each got.

#1061 chore: add SECURITY.md
  .github/SECURITY.md
Labels: chore, docs

#1065 docs(ls): document the toString() override
  README.md
  src/ls.js
Labels: docs

#1066 docs(chmod): briefly mention Windows file perms
  README.md
  src/chmod.js
Labels: docs

#959 sed with -i option now runs silently
  src/sed.js
  test/sed.js
Labels: fix, bash compat, breaking

#1057 Feature/grep n
  README.md
  src/grep.js
  test/grep.js
Labels: feature, bash compat

#1069 chore: remove codecov devDependency
  package.json
Labels: chore

#1072 chore: update deps
  package.json
Labels: chore

#1073 test(cp): fix cp -Ru test cases
  test/cp.js
Labels: test

#869 Add preserve option to cp
  README.md
  src/cp.js
  test/cp.js
Labels: feature, bash compat
