Repository shelljs/shelljs, pull requests merged in 2023-11, with the labels that each got.

#1139 chore: update nyc to v15
  .github/workflows/main.yml
  package.json
Labels: chore

#1141 chore: keep node < 16 around longer
  .github/workflows/main.yml
Labels: chore

#1138 chore: remove codecov token
  .github/workflows/main.yml
Labels: chore

#1142 test: add coverage for exit function
  shell.js
  test/echo.js
  test/exec.js
  test/exit.js
  test/popd.js
  test/pushd.js
  test/utils/mocks.js
Labels: refactor, test, test coverage

#1135 Exports shell.js and make.js on package.json
  package.json
Labels: refactor
