Repository shelljs/shelljs, pull requests merged in 2025-03, with the labels that each got.

#1190 refactor: prefer includes() over indexOf()
  src/chmod.js
  src/which.js
  test/config.js
  test/find.js
  test/ls.js
  test/set.js
  test/touch.js
  test/which.js
Labels: refactor

#1191 chore: commit package-lock.json
  .npmrc
  package-lock.json
Labels: chore

#1193 chore: update ava dep
  package-lock.json
  package.json
Labels: chore

#1119 Explicitly require commands
  shell.js
Labels: refactor

#1194 refactor: follow up fixes for static imports
  commands.js
  package.json
  shell.js
Labels: fix, refactor

#1196 fix: add global.js and plugin.js to exports list
  package.json
Labels: fix

#1198 test: add tests for shelljs glob expansion
  test/config.js
Labels: test

#1199 chore: remove unused env var
  .github/workflows/main.yml
Labels: chore

#1200 fix: add package.json to exports list
  package.json
Labels: fix, low priority

#1201 chore: update deps
  package-lock.json
  package.json
Labels: chore

#1203 chore: rename master -> main
  README.md
  RELEASE.md
Labels: chore, docs

#1204 refactor: avoid dependency cycle
  shell.js
  src/common.js
Labels: refactor
