Repository shelljs/shelljs, pull requests merged in 2025-04, with the labels that each got.

#1207 Enforce single quotes
  .editorconfig
Labels: chore, refactor

#1209 chore: update deps
  package-lock.json
Labels: chore

#1212 refactor: use require instead of import
  test/cat.js
  test/cd.js
  test/chmod.js
  test/cmd.js
  test/common.js
  test/config.js
  test/cp.js
  test/dirs.js
  test/echo.js
  test/env.js
  test/exec.js
  test/exit.js
  test/find.js
  test/global.js
  test/grep.js
  test/head.js
  test/ln.js
  test/ls.js
  test/mkdir.js
  test/mv.js
  test/pipe.js
  test/plugin.js
  test/popd.js
  test/pushd.js
  test/pwd.js
  test/rm.js
  test/sed.js
  test/set.js
  test/shjs.js
  test/sort.js
  test/tail.js
  test/tempdir.js
  test/test.js
  test/to.js
  test/toEnd.js
  test/touch.js
  test/uniq.js
  test/which.js
Labels: refactor, test

#1213 refactor: use expectations for t.throws
  test/cmd.js
  test/common.js
  test/exec.js
  test/plugin.js
  test/shjs.js
Labels: refactor, test

#1214 refactor: prefer promises over test.cb
  test/cmd.js
  test/exec.js
  test/pipe.js
Labels: refactor, test

#1215 refactor: allow es6 language features
  .eslintrc.json
  global.js
  scripts/check-node-support.js
  shell.js
  src/cat.js
  src/chmod.js
  src/cmd.js
  src/common.js
  src/dirs.js
  src/exec.js
  src/grep.js
  src/head.js
  src/ls.js
  src/mkdir.js
  src/rm.js
  src/sed.js
  src/sort.js
  src/tail.js
  src/tempdir.js
  src/test.js
  src/to.js
  src/toEnd.js
  src/touch.js
  src/uniq.js
  src/which.js
Labels: chore, refactor

#1217 refactor: use es6 class syntax for CommandError
  src/common.js
Labels: refactor

#1218 chore: update ava
  package-lock.json
  package.json
  test/.eslintrc.json
Labels: chore, dependencies

#1219 fix: cmd is compatible with node 22.10
  .github/workflows/main.yml
  scripts/check-node-support.js
  src/cmd.js
Labels: fix, exec

#1220 refactor: explicit handling for execa errors
  src/cmd.js
  test/cmd.js
  test/exec.js
  test/resources/exec/slow.js
Labels: refactor, exec, test coverage

#1206 Add -B and -A options to grep
  README.md
  src/grep.js
  test/grep.js
  test/resources/grep/file3
Labels: feature, bash compat

#1222 refactor: change how internal errors are handled
  src/cmd.js
  test/cmd.js
Labels: refactor, exec, test coverage
